### ISSUE TITLE
Repository redirect breaks asset page?

### ISSUE THREAD

**Issue by ccressent** [sensu/bonsai#309]
[This page](https://bonsai.sensu.io/assets/sensu/sensu-aws-ec2-deregistration-handler) is stuck "Scanning your asset...". We recently renamed the associated repo from `sensu/sensu-aws-ec2-deregistration-handler` to `sensu/sensu-ec2-handler` and [the old repo URL](https://github.com/sensu/sensu-aws-ec2-deregistration-handler) is a redirect to [the new repo URL](https://github.com/sensu/sensu-ec2-handler).

Could it be the cause of the breakage?

**Comment by pzupan** [comment]
It looks like there is a compilation error.  One of the release assets is missing.

**Comment by ccressent** [comment]
It looks like it got out of that "Scanning your asset..." state after a while and indeed now it's showing a "compilation" error. The asset is not really missing; the repository has changed name and the assets are now named differently. See [the plugin's release page](https://github.com/sensu/sensu-ec2-handler/releases).

The issue seems to be that while Bonsai follows the redirect to the new repo, it keeps using the old name to construct what the `.tar.gz` file names ought to be. This is not incorrect _per se_, the asset name on Bonsai is still `sensu/sensu-aws-ec2-deregistration-handler` after all, but this is an unforeseen consequence of renaming repositories on Github and it will need to be fixed/handled one way or another.

The Bonsai configuration suggests that `#{repo}` should be the new repo name though?
```
- arch: amd64
  filter:
  - entity.system.os == 'linux'
  - entity.system.arch == 'amd64'
  platform: linux
  sha_filename: "#{repo}_#{version}_sha512-checksums.txt"
  asset_filename: "#{repo}_#{version}_linux_amd64.tar.gz"
```

I haven't though of the best solution for this; I'm just raising this as an issue.
